var allCurrencies = [{v: "", t: "USD - United States Dollar"},
{v: "", t: "EUR - Euro"},
{v: "", t: "GBP - United Kingdom Pound"},
{v: "", t: "JPY - Japan Yen"},
{v: "", t: "CAD - Canada Dollar"},
{v: "", t: "AUD - Australia Dollar"},
{v: "", t: "CNY - China Yuan Renminbi"},
{v: "", t: "CHF - Switzerland Franc"},
{v: "", t: "SGD - Singapore Dollar"},
{v: "", t: "HKD - Hong Kong Dollar"},
{v: "", t: "AED - United Arab Emirates Dirham"},
{v: "", t: "AFN - Afghanistan Afghani"},
{v: "", t: "ALL - Albania Lek"},
{v: "", t: "AMD - Armenia Dram"},
{v: "", t: "ANG - Netherlands Antilles Guilder"},
{v: "", t: "AOA - Angola Kwanza"},
{v: "", t: "ARS - Argentina Peso"},
{v: "", t: "AWG - Aruba Guilder"},
{v: "", t: "AZN - Azerbaijan New Manat"},
{v: "", t: "BAM - Bosnia and Herzegovina Convertible Marka"},
{v: "", t: "BBD - Barbados Dollar"},
{v: "", t: "BDT - Bangladesh Taka"},
{v: "", t: "BGN - Bulgaria Lev"},
{v: "", t: "BHD - Bahrain Dinar"},
{v: "", t: "BIF - Burundi Franc"},
{v: "", t: "BMD - Bermuda Dollar"},
{v: "", t: "BND - Brunei Darussalam Dollar"},
{v: "", t: "BOB - Bolivia Boliviano"},
{v: "", t: "BRL - Brazil Real"},
{v: "", t: "BSD - Bahamas Dollar"},
{v: "", t: "BTN - Bhutan Ngultrum"},
{v: "", t: "BWP - Botswana Pula"},
{v: "", t: "BYR - Belarus Ruble"},
{v: "", t: "BZD - Belize Dollar"},
{v: "", t: "CAD - Canada Dollar"},
{v: "", t: "CDF - Congo/Kinshasa Franc"},
{v: "", t: "CLP - Chile Peso"},
{v: "", t: "COP - Colombia Peso"},
{v: "", t: "CRC - Costa Rica Colon"},
{v: "", t: "CUC - Cuba Convertible Peso"},
{v: "", t: "CUP - Cuba Peso"},
{v: "", t: "CVE - Cape Verde Escudo"},
{v: "", t: "CZK - Czech Republic Koruna"},
{v: "", t: "DJF - Djibouti Franc"},
{v: "", t: "DKK - Denmark Krone"},
{v: "", t: "DOP - Dominican Republic Peso"},
{v: "", t: "DZD - Algeria Dinar"},
{v: "", t: "EGP - Egypt Pound"},
{v: "", t: "ERN - Eritrea Nakfa"},
{v: "", t: "ETB - Ethiopia Birr"},
{v: "", t: "EUR - Euro"},
{v: "", t: "FJD - Fiji Dollar"},
{v: "", t: "FKP - Falkland Islands (Malvinas) Pound"},
{v: "", t: "GEL - Georgia Lari"},
{v: "", t: "GGP - Guernsey Pound"},
{v: "", t: "GHS - Ghana Cedi"},
{v: "", t: "GIP - Gibraltar Pound"},
{v: "", t: "GMD - Gambia Dalasi"},
{v: "", t: "GNF - Guinea Franc"},
{v: "", t: "GTQ - Guatemala Quetzal"},
{v: "", t: "GYD - Guyana Dollar"},
{v: "", t: "HNL - Honduras Lempira"},
{v: "", t: "HRK - Croatia Kuna"},
{v: "", t: "HTG - Haiti Gourde"},
{v: "", t: "HUF - Hungary Forint"},
{v: "", t: "IDR - Indonesia Rupiah"},
{v: "", t: "ILS - Israel Shekel"},
{v: "", t: "IMP - Isle of Man Pound"},
{v: "", t: "INR - India Rupee"},
{v: "", t: "IQD - Iraq Dinar"},
{v: "", t: "IRR - Iran Rial"},
{v: "", t: "ISK - Iceland Krona"},
{v: "", t: "JEP - Jersey Pound"},
{v: "", t: "JMD - Jamaica Dollar"},
{v: "", t: "JOD - Jordan Dinar"},
{v: "", t: "KES - Kenya Shilling"},
{v: "", t: "KGS - Kyrgyzstan Som"},
{v: "", t: "KHR - Cambodia Riel"},
{v: "", t: "KMF - Comoros Franc"},
{v: "", t: "KPW - Korea (North) Won"},
{v: "", t: "KRW - Korea (South) Won"},
{v: "", t: "KWD - Kuwait Dinar"},
{v: "", t: "KYD - Cayman Islands Dollar"},
{v: "", t: "KZT - Kazakhstan Tenge"},
{v: "", t: "LAK - Laos Kip"},
{v: "", t: "LBP - Lebanon Pound"},
{v: "", t: "LKR - Sri Lanka Rupee"},
{v: "", t: "LRD - Liberia Dollar"},
{v: "", t: "SL - Lesotho Loti"},
{v: "", t: "LYD - Libya Dinar"},
{v: "", t: "MAD - Morocco Dirham"},
{v: "", t: "MDL - Moldova Leu"},
{v: "", t: "MGA - Madagascar Ariary"},
{v: "", t: "MKD - Macedonia Denar"},
{v: "", t: "MMK - Myanmar (Burma) Kyat"},
{v: "", t: "MNT - Mongolia Tughrik"},
{v: "", t: "MOP - Macau Pataca"},
{v: "", t: "MRO - Mauritania Ouguiya"},
{v: "", t: "MUR - Mauritius Rupee"},
{v: "", t: "MVR - Maldives (Maldive Islands) Rufiyaa"},
{v: "", t: "MWK - Malawi Kwacha"},
{v: "", t: "MXN - Mexico Peso"},
{v: "", t: "MYR - Malaysia Ringgit"},
{v: "", t: "MZN - Mozambique Metical"},
{v: "", t: "NAD - Namibia Dollar"},
{v: "", t: "NGN - Nigeria Naira"},
{v: "", t: "NIO - Nicaragua Cordoba"},
{v: "", t: "NOK - Norway Krone"},
{v: "", t: "NPR - Nepal Rupee"},
{v: "", t: "NZD - New Zealand Dollar"},
{v: "", t: "OMR - Oman Rial"},
{v: "", t: "PAB - Panama Balboa"},
{v: "", t: "PEN - Peru Nuevo Sol"},
{v: "", t: "PGK - Papua New Guinea Kina"},
{v: "", t: "PHP - Philippines Peso"},
{v: "", t: "PKR - Pakistan Rupee"},
{v: "", t: "PLN - Poland Zloty"},
{v: "", t: "PYG - Paraguay Guarani"},
{v: "", t: "QAR - Qatar Riyal"},
{v: "", t: "RON - Romania New Leu"},
{v: "", t: "RSD - Serbia Dinar"},
{v: "", t: "RUB - Russia Ruble"},
{v: "", t: "RWF - Rwanda Franc"},
{v: "", t: "SAR - Saudi Arabia Riyal"},
{v: "", t: "SBD - Solomon Islands Dollar"},
{v: "", t: "SCR - Seychelles Rupee"},
{v: "", t: "SDG - Sudan Pound"},
{v: "", t: "SEK - Sweden Krona"},
{v: "", t: "SHP - Saint Helena Pound"},
{v: "", t: "SLL - Sierra Leone Leone"},
{v: "", t: "SOS - Somalia Shilling"},
{v: "", t: "SPL* - Seborga Luigino"},
{v: "", t: "SRD - Suriname Dollar"},
{v: "", t: "STD - São Tomé and Príncipe Dobra"},
{v: "", t: "SVC - El Salvador Colon"},
{v: "", t: "SYP - Syria Pound"},
{v: "", t: "SZL - Swaziland Lilangeni"},
{v: "", t: "THB - Thailand Baht"},
{v: "", t: "TJS - Tajikistan Somoni"},
{v: "", t: "TMT - Turkmenistan Manat"},
{v: "", t: "TND - Tunisia Dinar"},
{v: "", t: "TOP - Tonga Pa'anga"},
{v: "", t: "TRY - Turkey Lira"},
{v: "", t: "TTD - Trinidad and Tobago Dollar"},
{v: "", t: "TVD - Tuvalu Dollar"},
{v: "", t: "TWD - Taiwan New Dollar"},
{v: "", t: "TZS - Tanzania Shilling"},
{v: "", t: "UAH - Ukraine Hryvnia"},
{v: "", t: "UGX - Uganda Shilling"},
{v: "", t: "UYU - Uruguay Peso"},
{v: "", t: "UZS - Uzbekistan Som"},
{v: "", t: "VEF - Venezuela Bolivar"},
{v: "", t: "VND - Viet Nam Dong"},
{v: "", t: "VUV - Vanuatu Vatu"},
{v: "", t: "WST - Samoa Tala"},
{v: "", t: "XAF - Communauté Financière Africaine (BEAC) CFA Franc BEAC"},
{v: "", t: "XCD - East Caribbean Dollar"},
{v: "", t: "XDR - International Monetary Fund (IMF) Special Drawing Rights"},
{v: "", t: "XOF - Communauté Financière Africaine (BCEAO) Franc"},
{v: "", t: "XPF - Comptoirs Français du Pacifique (CFP) Franc"},
{v: "", t: "YER - Yemen Rial"},
{v: "", t: "ZAR - South Africa Rand"},
{v: "", t: "ZMW - Zambia Kwacha"},
{v: "", t: "ZWD - Zimbabwe Dollar"}]

function processCurrencies(){
	for(var i = 0; i < allCurrencies.length; i++){
		allCurrencies[i].v = allCurrencies[i].t.substring(0,3);
	}	
}
function addCurrencies(){
	processCurrencies();
	for(var i = 0; i < allCurrencies.length; i++){
		$('#gcurrency').append($('<option>', {
			value: allCurrencies[i].v,
			text: allCurrencies[i].t
		}));
	}
}